syntax = "proto3";
package ccsds.cdds.v1.td; 
import "types.proto";
import "tracking.proto";

/**
 * This is the gRPC definition of the CDDS Tracking Data Service returning raw tracking data 
 * as produced by the terminal facilitating the space link communication.
 */
service TrackingDataServiceProvider {

    /**
     * Returns a list of endpoints authorized for an authenticated user.
     */
    rpc getEndpoints(NoArg) returns (TrackingDataServiceEndpointList);

    /**
     * Opens a tracking data endpoint: A stream to receive raw tracking data according 
     * to the requested tracking data type.
     *
     * The service requires the following metadata when calling the open tracking data endpoint method:<br/><br/>
     *      1) td-endpoint-bin = JSON encoded TrackingDataServiceEndpoint using the binary marshaller<br/><br/>
     *
     * The TD service endpoint is authorized for the authenticated user. If not authorized,
     * the method call will fail.
     */ 
    rpc openTrackingDataServiceEndpoint(NoArg) returns (stream TrackingDataMessage);
}

message TrackingDataServiceEndpoint {
    /**
     * The CDDS service version of this service
     */
    uint32 serviceVersion = 1;

    /**
     * The name of the service provider organization providing the tracking data service
     */
    string serviceProvider = 10;

    /**
     * The terminal providing the tracking data service
     */
    optional string terminal = 20;

    /**
     * The serviceUser (spacecraft) for which tracking data shall be delivered
     */
    string serviceUser = 30;

    /**
     * The endpoint provided by the provider contains all available tracking data types available for the service user.
     * The endpoint included as metadata to the gRPC method open tracking data endpoint method shall
     * include tracking data types requested by the service user. The requested tracking data types shall be subset of the 
     * tracking data types available from the provider. If the user provides an empty list of tracking data types,
     * the provider shall deliver all tracking data types configured for this endpoint.
     */ 
    repeated TrackingDataType trackingDataType = 40; 

    /**
     * The QoS used for the provisioning of tracking data messages
     */
    EnumQoS qos = 50;

    /**
     * An optional endpoint name to distinguish endpoints;
     * for instance for spacecrafts supporting multiple bands.
     */
    optional string endpointName = 60;
}

/**
 * List of endpoints
 */
message TrackingDataServiceEndpointList {

    /**
     * The list of endpoints
     */ 
    repeated TrackingDataServiceEndpoint endpoints = 1;
} 

/**
 * This enum identifies the observation types as an enum
 */
enum TrackingDataType {
  TRACKING_DATA_TYPE_UNSPECIFIED = 0;

  DOPPLER_INSTANTANEOUS = 1;
  DOPPLER_INTEGRATED = 2;
  RANGE = 3;
  CARRIER_POWER = 4;
  CARRIER_POWER_TO_NOISE_SPECTRAL_DENSITY = 5;
  RANGING_POWER_TO_NOISE_SPECTRAL_DENSITY = 6;
  RECEIVE_FREQUENCY = 7;
  TRANSMIT_FREQUENCY = 8;
  TRANSMIT_FREQUENCY_RATE = 9;
  ANTENNA_ANGLES = 10;
}
