syntax = "proto3";
package ccsds.cdds.tm;
import "cdds-service-provider.proto";
import "cdds-tm-service.proto";

message TmServiceConfiguration {

    /**
     * A list od TM provider addresses.
     * The serviceProvider and optionally the terminal field link the 
     * provider addresses to the endpoints.
     * Note: the addresses and the endpoints can have an m:n relationship
     */
    repeated ServiceProviderAddress tmProviderAddresses = 1;    

    /**
     * The list of available TM endpoints, linked by serviceProvider and optionally
     * terminal to the tcProviderAddressList
     */
    repeated TmServiceEndpoint tmEndpoints = 10;
}

