syntax = "proto3";
package ccsds.cdds.v1.control;
import "types.proto"; 
import "control.proto";

/**
 * This is the gRPC definition of the CDDS Control Service to invoke ground station control directives.
 */
service ControlServiceProvider {

    /**
     * Returns a list of endpoints authorized for an authenticated user.
     */
    rpc getEndpoints(NoArg) returns (ControlServiceEndpointList);
   
    /**
     * Opens a control service endpoint: a bi-directional stream to send control directives and receive directive reports.
     * 
     * The returned directive reports provide information about directive request acceptance, 
     * directive execution and execution failures.
     * 
     * The service requires the following metadata when calling the service method:<br/><br/>
     *      1) control-endpoint-bin = JSON encoded ControlServiceEndpoint using the binary marshaller<br/><br/>
     *
     * The control service endpoint is authorized for the authenticated user. If not authorized,
     * the method call will fail.
     */ 
    rpc openControlEndpoint(stream ControlDirective) returns (stream DirectiveReport); 
}

/**
 * Allows the identification of a service endpoint in terms
 * of the parameters provided below.
 */
message ControlServiceEndpoint {
    /**
     * The CDDS service version of this service
     */
    uint32 serviceVersion = 1;

    /**
     * The name of the service provider organization providing the control service
     */
    string serviceProvider = 10;

    /**
     * The name of the terminal providing the control service
     */
    optional string terminal = 20;

    /**
     * The service user (spacecraft) for which control shall be provided
     */
    string serviceUser = 30;

    /**
     * The Object identifier list of the Functional Resource Directives available for this endpoint
     */
    repeated FunctionalResourceDirectiveName functionalResourceDirectives = 40;

    /**
     * The list of generic control directives available for this endpoint
     */
    repeated string genericDirectiveIds = 50;

    /**
     * An optional endpoint name to distinguish endpoints;
     * for instance for spacecrafts supporting multiple bands.
     */
    optional string endpointName = 60;
}

/**
 * List of endpoints
 */
message ControlServiceEndpointList {

    /**
     * The list of endpoints
     */ 
    repeated ControlServiceEndpoint endpoints = 1;
}

/**
 * identifies a Functional Resource Directive by OID and optionally by the instance number
 */
message FunctionalResourceDirectiveName {
    
    /**
     * The Directive Object Identifier
     */
    ObjectIdentifier functionalResourceDirective = 1;

    /**
     * The optional Functional Resource Instance number
     */
    optional uint64 functionalResourceInstance = 10;
}

