syntax = "proto3";
package ccsds.cdds.tc;
import "types.proto"; 
import "telecommand.proto";

/**
 * This is the gRPC definition of the CDDS TC Service for uplink of CLTUs or Telecommand frames.
 */
service TcServiceProvider {

     /**
     * Returns a list of endpoints authorized for an authenticated user.
     */
    rpc getEndpoints(NoArg) returns (TcServiceEndpointList);
   
    /**
     * Opens a TC endpoint: a bi-directional telecommand stream to send TC radiation request
     * carrying a CLTU or a TC frame.
     * The returned stream will receive the TC reports reporting on radiation, 
     * provider states uplink failures.
     * 
     * The service requires the following metadata when calling the service method:<br/><br/>
     *      1) tc-endpoint-bin = JSON encoded TcServiceEndpoint using the binary marshaller<br/><br/>
     *
     * The tc-endpoint-bin is authorized for the authenticated user. If not authorized,
     * the method call will fail.
     */ 
    rpc openTelecommandEndpoint(stream TelecommandMessage) returns (stream TelecommandReport); 
}

/**
 * Allows the identification of a service endpoint in terms
 * of the parameters provided below.
 */
message TcServiceEndpoint {
    /**
     * The CDDS service version of this service
     */
    uint32 serviceVersion = 1;

    /**
     * The name of the service provider organization providing the TC service
     */
    string serviceProvider = 10;

    /**
     * The name of the terminal providing the TC service
     */
    optional string terminal = 20;

    /**
     * The service user (spacecraft) for which TC shall be delivered
     */
    string serviceUser = 30;


    /**
     * Indicates the use of the endpoint for uplink of CLTU,
     * or a TC VC when the TC User provides TC frames for radiation.
     */
    oneof type {
        bool        cltu = 40;
        GvcIdList   gvcIds = 50;
    }

    /**
     * An optional endpoint name to distinguish endpoints;
     * for instance for spacecrafts supporting multiple bands.
     */
    optional string endpointName = 60;
}

/**
 * List of endpoints
 */
message TcServiceEndpointList {

    /**
     * The list of endpoints
     */ 
    repeated TcServiceEndpoint endpoints = 1;
} 

