syntax = "proto3";

package ccsds.cdds.v1;

import "types.proto";

/**
 * The control directive is either of generic type or compliant to a functional resource.
 */
message ControlDirective {

    oneof directive {

        /**
         *  Requests the invocation of a generic control directive
         */
        GenericControlDirective genericControlDirective = 1;

        /**
         *  Requests the invocation of a Functional Resource directive
         */
        FunctionalResourceDirective functionalResourceControlDirective = 10;
    }
}

/**
 * The generic control directive allows invocation of 
 * control directive identified by an identifier,
 * known to both, the CDDS User and CDDS Provider.
 */
message GenericControlDirective {

   /**
     * The invocation identifier is a unique identifier of one invocation of
     * a control directive.
     */
    uint32 invocationId = 1;
    
    /**
     * The directive identifier uniquely identifies a control directive
     * known to both, the CDDS User and CDDS Provider.
     */
    string directiveId = 10;

    /**
     * The qualifiers of the directive with identifier and value.
     */
    repeated GenericQualifier directiveQualifiers = 20;

}

/**
 * The generic qualifier has an identifier and a value.
 */ 
message GenericQualifier {

    /**
     * Identifies the qualifier for a given directive.
     * Scope: Within one given directive 
     */ 
    string qualifierId = 1;

    /**
     * The value of the qualifier.
     */
    Value qualifierValue = 10;
}

message FunctionalResourceDirective {

    /**
     * The invocation identifier is a unique identifier of one invocation of
     * a control directive.
     */
    uint32 invocationId = 1;

    /**
     * The Object Identifier of the Functional Resource Directive.
     * Note: The Object Identifier includes the Functional Resource Object Identifier.
     */
    ObjectIdentifier functionalResourceDirectiveIdentifier = 10;

   /**
     * The instance number of the Functional Resource
     * for which the directive is invoked.
     */
    uint64 functionalResourceInstance = 20;    

    /**
     * An optional human readable description of the directive
     */
    optional string directiveDescription = 30;

    /**
     * The qualifier of the invoked directive
     */
     repeated QualifierValue qualifierValues  = 40;
}
/**
 * A qualifier value.
 */
message QualifierValue {
    
    /**
     * This OID identifies the qualifier
     */ 
    ObjectIdentifier qualifierId = 1;

    /**
     * An optional human readable description of the qualifier.
     */
    optional string description = 10;

    /**
     * The Type OID identifying the type of the value. It is optional if the type is identified by other means
     */ 
    optional ObjectIdentifier parameterTypeId = 20;

    /**
     * The encoded value of the directive qualifier value. The value is encoded e.g. as Protobuf
     */
    bytes encodedQualifierValue = 30;
}

message DirectiveReport {
    /**
     * The production state of the CDDS Ground Station Control Service Provider.
     */
    ProductionState productionState = 1;

    /**
     * The invocation identifier is referring to a previously invoked  
     * control directive. If no directive has been ever invoked, this and all following fields shall be omitted.
     */
    uint32 invocationId = 10;

    /**
     * The result is informing about the outcome of a directive execution or a rejected directive.
     */
    DirectiveResult result = 20;

    /**
     * In case of a rejected ot execution error, the diagnostic shall provide more information
     */
    DirectiveExecutionDiagnostic diagnostic = 30;
}

/**
 * The directive result is used to report on the execution of directives.
 */ 
enum DirectiveResult {
    INVALID_DIRECTIVE_RESULT = 0;       // not initialized
    ACCEPTED = 1;                       // The directive has been accepted for execution
    REJECTED = 2;                       // The directive has been rejected for execution
    EXECUTED = 3;                       // The directive has been successfully executed
    EXECUTION_ERROR = 4;                // The directive execution had an error
}

/**
 * The directive execution diagnostic provides diagnostic information
 * for diagnostic rejected directives or directive execution errors.
 */
enum DirectiveExecutionDiagnostic {
    INVALID_DIRECTIVE_DIAGNOSTIC = 0;   // not initialized
    UNKNOWN_DIRECTIVE = 1;              // The directive is not known to the provider
    UNKNOWN_QUALIFIER = 2;              // The directive has an unknown directive qualifier
    QUALIFIER_OUT_OF_RANGE = 3;         // At least one directive qualifier was out of range    
    UNAUTHORIZED = 4;                   // The directive execution was not authorized to the service user
    OTHER = 5;                          // Any other error preventing successful directive execution
}