syntax = "proto3";

package ccsds.cdds.v1;

import "types.proto";

/**
 * A monitoring message can deliver lists of GenericMonitoringParameter and
 * FunctionalResourceParameter. At the end of the monitoring cycle of the endpoint the
 * monitoring message shall deliver for the parameters if this endpoint</br>
 *  - all parameters (cyclic monitoring)</br>
 *  - all parameter changed compared to the last delivery cycle (on-change monitoring)</br></br>
 * 
 * If the number of parameters exceeds a limit set forth by the provider, the parameters
 * may be distributed among several monitoring messages.
 * Events occurring for Functional Resources are reported immediately as they occur.
 * Implementations may decide to limit the frequency of reported events.
 */
message MonitoringMessage {
 
  /**
   * The production state of the CDDS Monitoring Service Provider.
   */
  ProductionState productionState = 1;

  /**
   * A Monitoring Message can carry generic monitoring parameters.
   */
  repeated GenericMonitoringParameter genericMonitoringParameters = 10;

  /**
   * A Monitoring Message can carry Functional Resource Parameters. 
   */
  repeated FunctionalResourceParameter functionalResourceParameters = 20;

  /**
   * A monitoring message can carry Functional Resource Events.
   */
  repeated FunctionalResourceEvent functionalResourceEvents = 30;
}

/**
 * Generic Monitoring Parameters reports any sort of generic
 * monitoring parameter. Generic monitoring parameters have to be 
 * defined and agreed between the CDDS Provider and the CDDS User.
 */
message GenericMonitoringParameter {

  /**
   * A unique identifier of the monitoring parameter.
   * The identifier has to be unique within the provided monitoring service.
   */
  string identifier = 1;

  /**
   * The times stamp when the monitoring parameter was generated.
   */
  DateTime timeStamp = 10;

  /**
   * The value of the monitoring parameter.
   * The value is qualified to indicate if the value is valid
   * and has an alarm associated to it.
   */
  QualifiedValue qualifiedValue = 20;
}


/**
 * Functional Resource Parameters reports parameters of Functional Resources.
 * Functional Resources follow either SANA registered Functional Resource definitions
 * or private Functional Resource definitions.
 */
message FunctionalResourceParameter {

  /**
   * The Object Identifier of the Functional Resource Parameter.
   */
  ObjectIdentifier functionalResourceParameterIdentifier = 1;

  /**
   * The instance number of the Functional Resource
   * for which the parameter is reported for.
   */
  uint64 functionalResourceInstance = 10;

  /**
   * The times stamp when the monitoring parameter was generated.
   */  
  DateTime timeStamp = 20;

  /**
   * The value of the of the functional resource parameter is encoded again
   * as a protobuf type. Such a protobuf specification is external to this
   * specification.
   */
  EncodedQualifiedValue parameterValue = 30;

}

/**
 * Functional Resource Events report events specified for Functional Resources.
 * Functional Resources follow either SANA registered Functional Resource definitions
 * or private Functional Resource definitions.
 */
message FunctionalResourceEvent {

  /**
   * The Object Identifier of the Functional Resource Parameter.
   */
  ObjectIdentifier functionalResourceEventIdentifier = 1;

  /**
   * The instance number of the Functional Resource
   * for which the event is reported for.
   */
  uint64 functionalResourceInstance = 10;

  /**
   * The times stamp when the monitoring event was generated.
   */  
  DateTime timeStamp = 20;

  /**
   * The event values of the of the functional resource parameter is encoded again
   * as a protobuf type. Such a protobuf specification is external to this
   * specification.
   */
  repeated EncodedQualifiedValue eventValue = 30;

}